"""Sync models

Revision ID: b6d874277cd9
Revises: 003_semantic_search
Create Date: 2026-08-13 00:06:24.473253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d874277cd9'
down_revision: Union[str, None] = '003_semantic_search'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('current_stage', sa.String(), nullable=True))
    op.add_column('analysis_jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('analysis_jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('analysis_jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('analysis_jobs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_analysis_jobs_id'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_repository_id'), table_name='analysis_jobs')
    op.drop_column('analysis_jobs', 'current_step')
    op.add_column('analysis_snapshots', sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_analysis_snapshots_id'), table_name='analysis_snapshots')
    op.drop_index(op.f('ix_analysis_snapshots_is_latest'), table_name='analysis_snapshots')
    op.drop_index(op.f('ix_analysis_snapshots_repository_id'), table_name='analysis_snapshots')
    op.drop_constraint(op.f('fk_analysis_snapshots_analysis_job_id_analysis_jobs'), 'analysis_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_snapshots_analysis_job_id_analysis_jobs'), 'analysis_snapshots', 'analysis_jobs', ['analysis_job_id'], ['id'])
    op.add_column('repositories', sa.Column('managed_path', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('detected_languages', sa.JSON(), nullable=True))
    op.add_column('repositories', sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('last_analyzed_commit', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_source_url'), table_name='repositories')
    op.drop_column('repositories', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_repositories_source_url'), 'repositories', ['source_url'], unique=False)
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.drop_column('repositories', 'created_at')
    op.drop_column('repositories', 'last_analyzed_commit')
    op.drop_column('repositories', 'last_analyzed_at')
    op.drop_column('repositories', 'detected_languages')
    op.drop_column('repositories', 'managed_path')
    op.drop_constraint(op.f('fk_analysis_snapshots_analysis_job_id_analysis_jobs'), 'analysis_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_snapshots_analysis_job_id_analysis_jobs'), 'analysis_snapshots', 'analysis_jobs', ['analysis_job_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_analysis_snapshots_repository_id'), 'analysis_snapshots', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_snapshots_is_latest'), 'analysis_snapshots', ['is_latest'], unique=False)
    op.create_index(op.f('ix_analysis_snapshots_id'), 'analysis_snapshots', ['id'], unique=False)
    op.drop_column('analysis_snapshots', 'analyzed_at')
    op.add_column('analysis_jobs', sa.Column('current_step', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_analysis_jobs_repository_id'), 'analysis_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_id'), 'analysis_jobs', ['id'], unique=False)
    op.alter_column('analysis_jobs', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('analysis_jobs', 'created_at')
    op.drop_column('analysis_jobs', 'completed_at')
    op.drop_column('analysis_jobs', 'started_at')
    op.drop_column('analysis_jobs', 'current_stage')
    # ### end Alembic commands ###
